version: '3'

services:
  centos-stream-8-pkg-builder:
    image: ghcr.io/${GITHUB_REPOSITORY}/centos-stream-8-pkg-builder:${GITHUB_SHA}
    build:
      context: build/centos-stream-8/pkg-builder
      cache_from:
        - ghcr.io/${GITHUB_REPOSITORY}/centos-stream-8-pkg-builder:cache
      args:
        BUILDKIT_INLINE_CACHE: 1

  centos-stream-8-intel-mvp-tdx-tdvf:
    image: ghcr.io/${GITHUB_REPOSITORY}/centos-stream-8-pkg-builder:${GITHUB_SHA}
    volumes:
      - ./build/centos-stream-8/intel-mvp-tdx-tdvf:/repo
    working_dir: /repo
    entrypoint:
      - /repo/build.sh

  centos-stream-8-intel-mvp-tdx-libvirt:
    image: ghcr.io/${GITHUB_REPOSITORY}/centos-stream-8-pkg-builder:${GITHUB_SHA}
    volumes:
      - ./build/centos-stream-8/intel-mvp-tdx-libvirt:/repo
    working_dir: /repo
    entrypoint:
      - /repo/build.sh

  centos-stream-8-intel-mvp-tdx-guest-shim:
    image: ghcr.io/${GITHUB_REPOSITORY}/centos-stream-8-pkg-builder:${GITHUB_SHA}
    volumes:
      - ./build/centos-stream-8/intel-mvp-tdx-guest-shim:/repo
    working_dir: /repo
    entrypoint:
      - /repo/build.sh

  centos-stream-8-intel-mvp-tdx-guest-grub2:
    image: ghcr.io/${GITHUB_REPOSITORY}/centos-stream-8-pkg-builder:${GITHUB_SHA}
    volumes:
      - ./build/centos-stream-8/intel-mvp-tdx-guest-grub2:/repo
    working_dir: /repo
    entrypoint:
      - /repo/build.sh

  centos-stream-8-intel-mvp-spr-qemu-kvm:
    image: ghcr.io/${GITHUB_REPOSITORY}/centos-stream-8-pkg-builder:${GITHUB_SHA}
    volumes:
      - ./build/centos-stream-8/intel-mvp-spr-qemu-kvm:/repo
    working_dir: /repo
    entrypoint:
      - /repo/build.sh

  centos-stream-8-intel-mvp-spr-kernel:
    image: ghcr.io/${GITHUB_REPOSITORY}/centos-stream-8-pkg-builder:${GITHUB_SHA}
    volumes:
      - ./build/centos-stream-8/intel-mvp-spr-kernel:/repo
    working_dir: /repo
    entrypoint:
      - /repo/build.sh
