name: PR Test Building SPR Kernel Package for CentOS Stream 8

on:
  push:
    branches: [usva]
  pull_request:
    branches: [usva]

jobs:
  build-packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Build tdx-guest-kernel
        uses: ./build/centos-stream-8/pkg-builder
        with:
          package: intel-mvp-tdx-guest-kernel
