name: PR Test Building Package for CentOS Stream 8

on:
  push:
    branches: [usva]
  pull_request:
    branches: [usva]

jobs:
  build-packages:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - uses: actions/checkout@v2.1.0
      - name: Build grub
        uses: ./build/centos-stream-8/pkg-builder
        with:
          package: intel-mvp-tdx-guest-grub2
      - name: Build shim package
        uses: ./build/centos-stream-8/pkg-builder
        with:
          package: intel-mvp-tdx-guest-shim
      - name: Build tdvf
        uses: ./build/centos-stream-8/pkg-builder
        with:
          package: intel-mvp-tdx-tdvf
      - name: Build qemu-kvm
        uses: ./build/centos-stream-8/pkg-builder
        with:
          package: intel-mvp-spr-qemu-kvm
      - name: Build libvirt
        uses: ./build/centos-stream-8/pkg-builder
        with:
          package: intel-mvp-tdx-libvirt
